import "./globals.css";
import { Inter } from "next/font/google";
import DataProvider from "@/context/DataContext";
import LoadingProgress from "@/components/LoadingProgress";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee Shop",
  description: "Generated by Coffee-shop-UI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider>
          <LoadingProgress>{children}</LoadingProgress>
        </DataProvider>
      </body>
    </html>
  );
}
